# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Java CI/CD with Gradle and Deploy to Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x ./homeworks/hw6/gradlew
      - name: Build with Gradle
        run: cd ./homeworks/hw6/; touch MyBooksApp.db; chmod 755 MyBooksApp.db; ./gradlew --scan --stacktrace build jar; mv ./build/MyBooksApp-1.0-SNAPSHOT.jar .
      - name: Commit to the repo
        uses: EndBug/add-and-commit@v4.4.0
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "damp-spire-88649" #Provide your unique app name here
          heroku_email: "tylerjshin@gmail.com" #Provide your Heroku email address here
          appdir: "homeworks/hw6" # <- This will point to the api folder in your project
