# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Plenum Java CI/CD with Gradle and Deploy to Heroku

on:
  push:
    branches: [ iteration3 ]
  pull_request:
    branches: [ iteration3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
      - name: install npm dependencies
        run:  (cd ./iterations/src/main/js  && npm install)
      - name: generate transpiled production frontend code
        run:  (cd ./iterations/src/main/js && npm run build)
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x ./iterations/gradlew
      - name: Build with Gradle
        run: (cd ./iterations && ./gradlew build jar && mv ./build/libs/iterations-1.0-SNAPSHOT.jar .)
      - name: Commit on the runner
        run: git config user.email "runner@github.com"; git config user.name "Runner"; git add *; git commit -m "None"
      - name: Deploy to Heroku
        env:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_QUORUM}}
          heroku_app_name: "warm-ridge-98252"
          heroku_email: "lee.hsinpei.melody@gmail.com"
          appdir: "iterations/"
        run: heroku git:remote -a warm-ridge-98252; git config user.password "$heroku_api_key"; git subtree push --prefix iterations heroku iteration3:master
